### ISSUE TITLE
 timemachine return code: 1

### ISSUE THREAD

**Issue by hydroflash** [munkireport/timemachine#12]
Receiving the following errors on 102 out of 150 clients.  Mixture of Ventura / Monterey on Intel / M1/ M2.

 timemachine Error: Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/timemachine", line 153, in <module>
    main()
  File "/usr/local/munkireport/scripts/timemachine", line 145, in main
    info = get_time_machine()
  File "/usr/local/munkireport/scripts/timemachine", line 68, in get_time_machine
    settings = AppleTMSettings.sharedSettings()
AttributeError: 'NoneType' object has no attribute 'sharedSettings'
WARNING: timemachine return code: 1

**Comment by tuxudo** [comment]
This will be fixed with the Python 3 version of the module.

**Comment by tuxudo** [comment]
Fixed with version v4.0 of module
