### ISSUE TITLE
Ventura / M1

### ISSUE THREAD

**Issue by CBBuerger** [munkireport/timemachine#9]
Running timemachine
    timemachine Error: Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/timemachine", line 153, in <module>
    main()
  File "/usr/local/munkireport/scripts/timemachine", line 145, in main
    info = get_time_machine()
  File "/usr/local/munkireport/scripts/timemachine", line 68, in get_time_machine
    settings = AppleTMSettings.sharedSettings()
AttributeError: 'NoneType' object has no attribute 'sharedSettings'
WARNING: timemachine return code: 1

**Comment by hydroflash** [comment]
I'm receiving the same errors on Intel machines also.

**Comment by tuxudo** [comment]
Will be fixed in the Python 3 version of the module.

**Comment by tuxudo** [comment]
Fixed with v4.0 of module
